### ISSUE TITLE
Плей-офф: замечания

### ISSUE THREAD

**Issue by FZambia** [shutalker/technopark-python#1]
Привет, у меня очень мало замечаний - практически все замечательно! 👍 

Вот эта ф-я бросилась в глаза огромным количеством обращений по индексу:

```python
def playoff(teamlist, team_amount):
    for stage in range(int(log2(team_amount))):
        step = int(pow(2, stage))
        for i in range(0, team_amount, (step * 2)):
            matchmaking(teamlist[i], teamlist[i + step])
            if teamlist[i + step]['scores'][-1][0] > teamlist[i]['scores'][-1][0]:
                teamlist[i], teamlist[i + step] = teamlist[i + step], teamlist[i]
            teamlist[i + step]['is_out'] = step
        print_playoff_grid(teamlist, step, team_amount)
```

Она не читаема - возможно ты сам понимаешь что в ней происходит, но мне тоже хотелось бы понимать:)

```python
def create_teamlist(names, teamlist):
    for name in names:
        team = dict.fromkeys(['name', 'opponents', 'scores', 'is_out'])
        team['name'], team['is_out'] = name, 0
        team['opponents'], team['scores'] = list(), list()
        teamlist.append(team)
```

можно было бы так написать:

```python
def create_teamlist(names):
    teams = []
    for name in names:
        team = {
            "name": name,
            "is_out": 0,
            "opponents": [],
            "scores": []
        }
        teams.append(team)
    return teams
```

На мой взгляд более читаемо. Плюс убрал сайд-эффект - модификацию списка из верхнего неймспейса, гораздо проще объявить список внутри ф-ии и вернуть его.

И последнее:

```python
log2(team_amount) - int(log2(team_amount)) != 0.0
```

Можно было просто `!= 0`

По стилю нет замечаний вообще - сразу видно, что используешь хороший редактор. + хорошо  переменные называешь. По логике тож норм.

**Comment by shutalker** [comment]
Исправил, теперь функция playoff должна выглядеть читабельнее.

**Comment by FZambia** [comment]
@shutalker вижу, отличная работа 👍
